name: Lettcode Solutions Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.5
            
